[project]
name = "dkg-phd-thesis"
r_version = "4.4.3"

[dependencies]
"broom.mixed" = "*"
car = "*"
careless = "*"
correlation = "*"
corrplot = "*"
cowplot = "*"
datawizard = "*"
dplyr = "*"
effectsize = "*"
flextable = "*"
forcats = "*"
ggdist = "*"
ggplot2 = "*"
ggrepel = "*"
ggridges = "*"
glue = "*"
gridExtra = "*"
here = "*"
iccbeta = "*"
interactions = "*"
knitr = "*"
lavaan = "*"
lme4 = "*"
lmerTest = "*"
officer = "*"
parameters = "*"
patchwork = "*"
performance = "*"
psych = "*"
purrr = "*"
readr = "*"
rmcorr = "*"
scales = "*"
see = "*"
semTools = "*"
stringr = "*"
svglite = "*"
tibble = "*"
tidyr = "*"
viridis = "*"
yaml = "*"
