# Power Analysis Configuration
params:
  n_lvl1: 3
  n_lvl2: [100, 300, 500]
  lvl1_effect_std: [0.10, 0.30, 0.50]
  lvl2_effect_std: [0.10, 0.30, 0.50]
  xlvl_effect_std: [0.10, 0.30, 0.50]
  icc: [0.10, 0.30, 0.50]
  rand_slope_std: [0.01, 0.09, 0.25]
  alpha: 0.05
  use_REML: TRUE
  n_sims: 1
  verbose: TRUE
  return_df: TRUE
  rand_seed: 8762
