# Power Analysis Configuration
params:
  n_lvl1: 3
  n_lvl2: [50, 100]
  lvl1_effect_std: [0.30]
  lvl2_effect_std: [0.30]
  xlvl_effect_std: [0.30]
  icc: [0.10, 0.30, 0.50]
  rand_slope_std: [0.09]
  alpha: 0.05
  use_REML: TRUE
  n_sims: 1
  verbose: TRUE
  return_df: TRUE
  rand_seed: 1879
