### request 1
POST http://localhost:8080/

### cloud unauthenticated request 1
curl -X POST http://localhost:8080 \
-H "Content-Type: application/json" \
-d '{
    "SurveyID": "SV_86vMYNR8SdVDfEi",
    "ResponseID": "R_2K1g4Q10yyaSzTe",
    "InformedConsent": "Yes",
    "ProlificPIDEmbedded": "",
    "ProlificPIDEntry": "",
    "FTEFlag": "",
    "LocationFlag": "",
    "AgeFlag": "",
    "LanguageFlag": "",
    "Phone": "",
    "LocalTZ": "",
    "Date": ""
}'
