params:
  gcp:
    project_id: dkg-phd-thesis
  secret_mgr:
    version_id: latest
  pubsub:
    required_keys:
      - SurveyID
      - ResponseID
      - InformedConsent
      - ProlificPIDEmbedded
      - ProlificPIDEntry
      - FTEFlag
      - LocationFlag
      - AgeFlag
      - LanguageFlag
      - Phone
      - LocalTZ
      - Dates
