params:
  gcp:
    project_id: dkg-phd-thesis
    version_id: latest
  gspread:
    secret_id: dkg-gsheets-sa-key
    use_method: key
    spreadsheet_id: 1KUawlkxvzI-FR15AULX-7MKxxbB3Sv3ZS5-LPoY8Vjw
    raw_contacts_sheet_name: raw_contacts
    clean_contacts_sheet_name: clean_contacts
