params:
  gcp:
    project_id: dkg-phd-thesis
  bq:
    dataset_id: qualtrics_db
    raw_table: raw_contact_directory
    raw_table_fields:
      - survey_id
      - response_id
      - start_date
      - end_date
      - finished
      - total_duration
      - timepoint
      - prolific_pid_entry
      - prolific_pid_embedded
      - informed_consent
      - fte_flag
      - location_flag
      - age_flag
      - language_flag
      - phone
      - local_tz
      - date
  clean_table: clean_contact_directory
  secret_mgr:
    version_id: latest
