params:
  gcp:
    project_id: dkg-phd-thesis
  bq:
    dataset_id: qualtrics_db
    raw_table: raw_contact_directory
    raw_table_fields:
      - survey_id
      - response_id
      - start_date
      - end_date
      - finished
      - total_duration
      - timepoint
      - prolific_pid_entry
      - prolific_pid_embedded
      - informed_consent
      - fte_flag
      - location_flag
      - age_flag
      - language_flag
      - phone
      - local_tz
      - date
    clean_table: clean_contact_directory
    clean_table_fields:
      - SURVEY_ID
      - RESPONSE_ID
      - START_DATE
      - END_DATE
      - FINISHED
      - TOTAL_DURATION
      - TIMEPOINT
      - PROLIFIC_PID_ENTRY
      - PROLIFIC_PID_EMBEDDED
      - INFORMED_CONSENT
      - FTE_FLAG
      - LOCATION_FLAG
      - AGE_FLAG
      - LANGUAGE_FLAG
      - PHONE
      - LOCAL_TZ
      - DATE
  secret_mgr:
    service_account_secret_id: dkg-gsheets-sa-key
    api_key_secret_id: cloud-fun-api-key-gsheets-2-bq
    version_id: latest
